name: cellular_automata_web
description: Web renderes and demos for the cellular_automata package.
version: 1.0.1
homepage: https://github.com/jimmyff/cellular_automata_web
author: Jimmy Forrester-Fellowes <jimmyff@jimmyff.uk>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  logging: ^0.11.3+1
  cellular_automata: ^1.0.0
  stagexl: ^1.2.0+3

dev_dependencies:
  test: ^1.3.0

# dependency_overrides:
#   cellular_automata:
#     path: ../cellular_automata
