name: cellular_automata_web_demos
description: Web demos utilising the cellular_automata & cellular_automata_web packages.
version: 1.0.0
homepage: https://github.com/jimmyff/cellular_automata_web
author: Jimmy Forrester-Fellowes <jimmyff@jimmyff.uk>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  cellular_automata: ^1.0.0
  cellular_automata_web: ^1.0.0
  stagexl: ^1.4.0
  color: '^2.0.2'

dev_dependencies:
  build_runner: ^0.9.2
  build_web_compilers: ^0.4.1
  logging: ^0.11.3+2

# dependency_overrides:
#   cellular_automata:
#     path: ../../cellular_automata
#   cellular_automata_web:
#     path: ../

web:
  compiler:
    debug: dartdevc

